### ISSUE TITLE
OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed

### ISSUE THREAD

**Issue by akshay-gr** [xero-gateway/xero_gateway#72]
Getting the below error while requesting got access token. 

````
2.1.0 :001 > gateway = XeroGateway::Gateway.new(Settings.xero.CONSUMER_KEY, Settings.xero.CONSUMER_SECRET)
 => #<XeroGateway::Gateway:0xc77c14c @xero_url="https://api.xero.com/api.xro/2.0", @client=#<XeroGateway::OAuth:0xc77c110 @csecret="KIPMDUFIYBY53QZBGCSCFBSJTMUKB6", @ctoken="0BMCUHKRFMU3X5TT9RISZSBPOUD2PH", @consumer_options={:site=>"https://api.xero.com", :request_token_path=>"/oauth/RequestToken", :access_token_path=>"/oauth/AccessToken", :authorize_path=>"/oauth/Authorize"}>> 
2.1.0 :002 > request_token = gateway.request_token
OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
	from /usr/local/rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/net/http.rb:920:in `connect'
	from /usr/local/rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/net/http.rb:920:in `block in connect'
	from /usr/local/rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/timeout.rb:82:in `block in timeout'
	from /usr/local/rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/timeout.rb:70:in `catch'
	from /usr/local/rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/timeout.rb:70:in `timeout'
	from /usr/local/rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/net/http.rb:920:in `connect'
	from /usr/local/rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/net/http.rb:863:in `do_start'
	from /usr/local/rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/net/http.rb:852:in `start'
	from /usr/local/rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/net/http.rb:1369:in `request'
	from /usr/local/rvm/gems/ruby-2.1.0@xero_api/gems/oauth-0.4.7/lib/oauth/consumer.rb:161:in `request'
	from /usr/local/rvm/gems/ruby-2.1.0@xero_api/gems/oauth-0.4.7/lib/oauth/consumer.rb:194:in `token_request'
	from /usr/local/rvm/gems/ruby-2.1.0@xero_api/gems/oauth-0.4.7/lib/oauth/consumer.rb:136:in `get_request_token'
	from /usr/local/rvm/gems/ruby-2.1.0@xero_api/gems/xero_gateway-2.1.0/lib/xero_gateway/oauth.rb:41:in `request_token'
	from (irb):2
	from /usr/local/rvm/gems/ruby-2.1.0@xero_api/gems/railties-4.2.0/lib/rails/commands/console.rb:110:in `start'
	from /usr/local/rvm/gems/ruby-2.1.0@xero_api/gems/railties-4.2.0/lib/rails/commands/console.rb:9:in `start'
	from /usr/local/rvm/gems/ruby-2.1.0@xero_api/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /usr/local/rvm/gems/ruby-2.1.0@xero_api/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /usr/local/rvm/gems/ruby-2.1.0@xero_api/gems/railties-4.2.0/lib/rails/commands.rb:17:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.1.0@xero_api/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
	from /usr/local/rvm/gems/ruby-2.1.0@xero_api/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `block in require'
	from /usr/local/rvm/gems/ruby-2.1.0@xero_api/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /usr/local/rvm/gems/ruby-2.1.0@xero_api/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
	from /home/rails/rails_work/brandom/xero_demo_api/bin/rails:8:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.1.0@xero_api/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `load'
	from /usr/local/rvm/gems/ruby-2.1.0@xero_api/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `block in load'
	from /usr/local/rvm/gems/ruby-2.1.0@xero_api/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /usr/local/rvm/gems/ruby-2.1.0@xero_api/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `load'
	from /usr/local/rvm/rubies/ruby-2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/rvm/rubies/ruby-2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
````

**Comment by nikz** [comment]
Hi Ashkay,

FYI that stacktrace includes your consumer key and secret, so I strongly suggest you rotate those using the Xero Developer portal.

Can you let me know what version of OpenSSL you're using on your sever/machine?

Thanks,

Nik

**Comment by akshay-gr** [comment]
thanks, Nik. I have changes keys. 
openssl version: OpenSSL 1.0.1 14 Mar 2012
Yes, I'm using it on my machine. Ubuntu 12.04

**Comment by nikz** [comment]
Hi Akshay,

I think the included certificates might be out of date - can you try telling Xero Gateway to use the newer SSL certificates?

I'll take a look at updating them this weekend.

Nik

**Comment by thechrisoshow** [comment]
I'm having the same issue. Do we think this is to do with the certs included in the gem?

**Comment by nikz** [comment]
@thechrisoshow Are you on Ubuntu? A friend mentioned Ubuntu removing a CA that Xero was using.

Sorry, I don't have time to look into it in detail right now, will hopefully be able to fix in the next couple of days.

Can you also let me know your openssl version?

**Comment by thechrisoshow** [comment]
No worries, I just thought you might have more information.

I'm on heroku cedar-14 (which is Ubuntu 14.04)
OpenSSL 1.0.1f 6 Jan 2014

There might be something fishy on my system as well (I'll have a look).

**Comment by akampjes** [comment]
FYI the solution is here: https://community.xero.com/developer/discussion/8447428

**Comment by nikz** [comment]
@akampjes thanks for that, we should be able to include the ca bundle in the gem fairly easily in the meantime, I'll work on that.

**Comment by thechrisoshow** [comment]
Hey @nikz,

What's involved with including the ca bundle? Anything I can do to help?

I need to start invoicin' yo!

-Chris

**Comment by armstrjare** [comment]
Hey @thechrisoshow and all,

Actually, the CA file is already included in the gem from a long time ago, and the functionality to specify it manually already exists. 

If you pass the :ca_file option to the Xero::Gateway initialisation, this will get propagated through to the OAuth::Consumer instance, and from there used to setup the Net::HTTP instance it uses to make HTTP requests.

```
# Use bundle included in gem, or, download as bundle from:
#    https://www.entrust.net/downloads/root_index.cfm
# and store locally.
ca_file = File.join(Bundler.rubygems.find_name('xero_gateway').first.full_gem_path, "lib", "xero_gateway", "ca-certificates.crt")

XeroGateway::PartnerApp.new(
  XERO[:consumer_key],
  XERO[:consumer_secret],
  :autorenew        => true,
  :private_key_file => ...,
  :ssl_client_cert  => ...,
  :ssl_client_key   => ..,
  :ca_file => ca_file
)
```

Let me know if you have any issues :-)

Jared

**Comment by nikz** [comment]
@armstrjare Potentially we should make this the default? Better to avoid issues first up I think,

**Comment by thechrisoshow** [comment]
Thanks @armstrjare - worked a charm!

*/me gets back to invoicing*

**Show me the money! Show me the money!**

**Comment by eltonbartel** [comment]
:ca_file => ca_file this change had fixed the issue for some months now . But again the error popped up exactly after Xero migrated their Certs to SHA2 from SHA1. What we need to avoid the below error
OpenSSL::SSL::SSLError (SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed):

**Comment by thechrisoshow** [comment]
Yep - I'm seeing this problem again too - do we need to update the CA file?

**Comment by nikz** [comment]
Going to close this one now, as I think it's resolved!
